name: C/C++ CI

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Docker build and push
      uses: azure/docker-login@v1
      with:
          login-server: vehicleregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
          docker buildx create --use --name multi-arch-builder
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx ls
          docker buildx build --platform linux/arm64 --push -t vehicleregistry.azurecr.io/vehicle-data-simulator-arm64:${{ github.run_number }} .
